name: 21cmfast
channels:
  - defaults
dependencies:
  - python=3.7
  - sphinxcontrib-htmlhelp
  - zlib
  - pip
  - libxml2
  - libffi
  - zipp
  - click
  - libgcc-ng
  - scipy
  - expat
  - pytest
  - libpng
  - jpeg
  - importlib_metadata
  - pyopenssl
  - ptyprocess
  - attrs
  - asn1crypto
  - gstreamer
  - pygments
  - blas
  - libstdcxx-ng
  - babel
  - libgfortran-ng
  - pyqt
  - freetype
  - six
  - pyparsing
  - pytest-openfiles
  - glib
  - ipython
  - sphinxcontrib-devhelp
  - traitlets
  - toml
  - jedi
  - cycler
  - more-itertools
  - idna
  - pycparser
  - pyyaml
  - yaml
  - qt
  - packaging
  - ipython_genutils
  - cffi
  - pytest-remotedata
  - mkl
  - chardet
  - xz
  - docutils
  - sqlite
  - snowballstemmer
  - fontconfig
  - pexpect
  - psutil
  - prompt_toolkit
  - atomicwrites
  - pytest-astropy
  - openssl
  - sphinx
  - alabaster
  - numpydoc
  - kiwisolver
  - pytest-arraydiff
  - intel-openmp
  - sphinxcontrib-qthelp
  - mkl_random
  - pickleshare
  - py
  - requests
  - wcwidth
  - readline
  - libuuid
  - numpy-base
  - tk
  - markupsafe
  - pysocks
  - sip
  - icu
  - gst-plugins-base
  - matplotlib
  - mkl_fft
  - ncurses
  - pytest-doctestplus
  - cryptography
  - imagesize
  - pluggy
  - tornado
  - sphinxcontrib-serializinghtml
  - certifi
  - backcall
  - wheel
  - astropy
  - dbus
  - jinja2
  - sphinxcontrib-applehelp
  - libxcb
  - pcre
  - parso
  - setuptools
  - python-dateutil
  - pytz
  - decorator
  - urllib3
  - numpy
  - tqdm
  - sphinxcontrib-jsmath
  - ca-certificates
  - libedit
  - twine
  - h5py
  - jupyter
  - nb_conda
  - pip:
      - pre-commit
