# Run template for simple 21cmfast runs

[CosmoParams]

[SimulationOptions]

[MatterOptions]
SOURCE_MODEL = 'CONST-ION-EFF'

[AstroParams]

[AstroOptions]
USE_EXP_FILTER = false
CELL_RECOMB = false
USE_UPPER_STELLAR_TURNOVER = false
USE_MINI_HALOS = false
USE_TS_FLUCT = false
INHOMO_RECO = false
HII_FILTER = 'sharp-k'
