# Run template for a small test run
#NOTE: To use this one should disable the default R_BUBBLE_MAX errors
#   by setting py21cmfast.config["ignore_R_BUBBLE_MAX_error"] = True

[CosmoParams]

[SimulationOptions]
HII_DIM=48
BOX_LEN=64

[MatterOptions]
USE_HALO_FIELD = false
HALO_STOCHASTICITY = false

[AstroParams]
R_BUBBLE_MAX = 50.0

[AstroOptions]
USE_EXP_FILTER = false
CELL_RECOMB = false
USE_UPPER_STELLAR_TURNOVER = false
USE_MINI_HALOS = false
USE_TS_FLUCT = true
INHOMO_RECO = true
HII_FILTER = 'sharp-k'
