# Run template for latest fiducial grid-based 21cmfast runs with molecularly cooled halos / PopIII stars

[CosmoParams]

[MatterParams]
USE_RELATIVE_VELOCITIES = true

[AstroParams]
R_BUBBLE_MAX = 50.0
M_TURN = 5.0

[AstroFlags]
USE_HALO_FIELD = false
HALO_STOCHASTICITY = false
USE_EXP_FILTER = false
CELL_RECOMB = false
USE_UPPER_STELLAR_TURNOVER = false
USE_MINI_HALOS = true
USE_TS_FLUCT = true
INHOMO_RECO = true
HII_FILTER = 'sharp-k'
