# Run template for latest fiducial grid-based 21cmfast runs with molecularly cooled halos / PopIII stars

[CosmoParams]

[SimulationOptions]

[MatterOptions]
LAGRANGIAN_SOURCE_GRIDS = false
USE_DISCRETE_HALOS = false
USE_CHMF_SAMPLER = false
USE_RELATIVE_VELOCITIES = true

[AstroParams]
R_BUBBLE_MAX = 50.0
M_TURN = 5.0

[AstroOptions]
USE_EXP_FILTER = false
CELL_RECOMB = false
USE_UPPER_STELLAR_TURNOVER = false
USE_MINI_HALOS = true
USE_TS_FLUCT = true
INHOMO_RECO = true
HII_FILTER = 'sharp-k'
