# Run template for reproducing Qin20 reference simulation results

[CosmoParams]

[UserParams]
USE_RELATIVE_VELOCITIES = false

[AstroParams]
F_STAR10 = -1.25
F_STAR7_MINI = -1.75
F_ESC10 = -1.22
F_ESC7_MINI = -2.22
ALPHA_STAR = 0.5
ALPHA_ESC = 0.0
M_TURN = 5.0 # not included in Qin20, so we set very low
t_STAR = 0.5
L_X = 40.5
X_RAY_SPEC_INDEX = 1.0
NU_X_THRESH = 500
R_BUBBLE_MAX = 50.0

[FlagOptions]
USE_HALO_FIELD = false
HALO_STOCHASTICITY = false
USE_EXP_FILTER = false
CELL_RECOMB = false
USE_MINI_HALOS = true
USE_CMB_HEATING = false
USE_LYA_HEATING = false
USE_TS_FLUCT = true
INHOMO_RECO = true
