channels:
  - defaults
  - conda-forge

dependencies:
  - pip
  - ipython
  - numpydoc
  - sphinx>=1.3
  - astropy  # need this here, because we base classes off it (and docs need that).
  - pyyaml
  - matplotlib
  - nbconvert>=6.4.5
  - pip:
    - sphinx-rtd-theme
    - setuptools_scm
    - bidict
    - nbsphinx
    - nbconvert>=6.4.5
